# Build and deploy Dockerfile to Cloud Run
# https://cloud.google.com/build/docs/build-config-file-schema
# https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run

substitutions:
  _REGION: "us-east4"
  _SERVICE_NAME: "shallweswim"
  _IMAGE_NAME: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/gcr/${_SERVICE_NAME}"

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: build-and-push
    entrypoint: bash
    args:
      - -c
      - |
        # Create a modern builder instance with docker-container driver
        docker buildx create --name builder --driver docker-container --use

        # Build, cache, and push in one atomic operation
        docker buildx build \
          --platform linux/amd64 \
          -t ${_IMAGE_NAME} \
          --cache-from=type=registry,ref=${_IMAGE_NAME}:buildcache \
          --cache-to=type=registry,ref=${_IMAGE_NAME}:buildcache,mode=max \
          --push \
          .
    env:
      - DOCKER_BUILDKIT=1

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: cloud_run_deploy
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_IMAGE_NAME}",
        "--region",
        "${_REGION}",
      ]

options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY
