"""Backwards compatibility - re-exports from core.feeds."""

from shallweswim.core.feeds import (
    FEED_CURRENTS,
    FEED_HISTORIC_TEMPS,
    FEED_LIVE_TEMPS,
    FEED_TIDES,
    PLOT_HISTORIC_TEMPS_2MO,
    PLOT_HISTORIC_TEMPS_12MO,
    PLOT_LIVE_TEMPS,
    CompositeFeed,
    CoopsCurrentsFeed,
    CoopsTempFeed,
    CoopsTidesFeed,
    CurrentsFeed,
    Feed,
    FeedName,
    HistoricalTempsFeed,
    MultiStationCurrentsFeed,
    NdbcTempFeed,
    NwisCurrentFeed,
    NwisTempFeed,
    PlotName,
    TempFeed,
    create_current_feed,
    create_temp_feed,
    create_tide_feed,
)

__all__ = [
    "FEED_CURRENTS",
    "FEED_HISTORIC_TEMPS",
    "FEED_LIVE_TEMPS",
    "FEED_TIDES",
    "PLOT_HISTORIC_TEMPS_2MO",
    "PLOT_HISTORIC_TEMPS_12MO",
    "PLOT_LIVE_TEMPS",
    "CompositeFeed",
    "CoopsCurrentsFeed",
    "CoopsTempFeed",
    "CoopsTidesFeed",
    "CurrentsFeed",
    "Feed",
    "FeedName",
    "HistoricalTempsFeed",
    "MultiStationCurrentsFeed",
    "NdbcTempFeed",
    "NwisCurrentFeed",
    "NwisTempFeed",
    "PlotName",
    "TempFeed",
    "create_current_feed",
    "create_temp_feed",
    "create_tide_feed",
]
