/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/app/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App Bootstrap
         * @description Return non-secret presentation metadata for the React app.
         */
        get: operations["app_bootstrap_api_app_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthy Status
         * @description API endpoint for service health check (used by Cloud Run).
         *
         *     Returns 200 if at least one location can serve data (fresh or stale).
         *     Returns 503 only if NO location has any data available.
         *
         *     This lenient check ensures single station outages don't mark the entire
         *     service unhealthy. For detailed per-feed health status, use /api/status.
         *
         *     Returns:
         *         True if service can serve at least one location
         *         Status code 200 if healthy, 503 if not healthy
         */
        get: operations["healthy_status_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/healthy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthy Status
         * @description API endpoint for service health check (used by Cloud Run).
         *
         *     Returns 200 if at least one location can serve data (fresh or stale).
         *     Returns 503 only if NO location has any data available.
         *
         *     This lenient check ensures single station outages don't mark the entire
         *     service unhealthy. For detailed per-feed health status, use /api/status.
         *
         *     Returns:
         *         True if service can serve at least one location
         *         Status code 200 if healthy, 503 if not healthy
         */
        get: operations["healthy_status_api_healthy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Locations
         * @description API endpoint that returns a list of all configured swimming locations.
         *
         *     Returns a summary of each location including code, name, coordinates,
         *     and whether data is currently available.
         *
         *     Returns:
         *         List of LocationSummary objects for all configured locations
         */
        get: operations["list_locations_api_locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All Locations Status
         * @description API endpoint that returns status information for all configured locations.
         *
         *     Returns:
         *         Dictionary mapping location codes to their status dictionaries
         *
         *     Raises:
         *         HTTPException: If no locations are configured
         */
        get: operations["all_locations_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{location}/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location Conditions
         * @description API endpoint that returns tide and temperature data for a specific location.
         *
         *     Args:
         *         location: Location code (e.g., 'nyc')
         *         shift: Time shift in minutes from current time (optional)
         *         at: Location-local ISO-8601 timestamp within 24 hours; overrides shift
         *
         *     Returns:
         *         JSON response with tide and temperature information
         *
         *     Raises:
         *         HTTPException: If the location is not configured
         */
        get: operations["location_conditions_api__location__conditions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{location}/currents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location Currents
         * @description API endpoint that returns current predictions for a specific location.
         *
         *     Args:
         *         location: Location code (e.g., 'nyc')
         *         shift: Time shift in minutes from current time (optional)
         *         at: Location-local ISO-8601 timestamp within 24 hours; overrides shift
         *
         *     Returns:
         *         CurrentsResponse object with current prediction details
         *
         *     Raises:
         *         HTTPException: If the location is not configured or doesn't support currents
         */
        get: operations["location_currents_api__location__currents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{location}/plots/current_tide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Tide Plot
         * @description Generate and serve a tide and current plot for the specified location.
         *
         *     Args:
         *         location: Location code (e.g., "nyc", "san")
         *         shift: Time shift in minutes from current time
         *         at: Location-local ISO-8601 timestamp within 24 hours; overrides shift
         *
         *     Returns:
         *         SVG image response with tide and current visualization
         */
        get: operations["get_current_tide_plot_api__location__plots_current_tide_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{location}/plots/historic_temps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Historic Temps Plot
         * @description Serve a historic temperature plot for the specified location.
         *
         *     Args:
         *         location: Location code (e.g., "nyc", "sfo")
         *         period: Time period - "2mo" for 2-month or "12mo" for full year
         *
         *     Returns:
         *         SVG image response with historic temperature visualization
         */
        get: operations["get_historic_temps_plot_api__location__plots_historic_temps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{location}/plots/live_temps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Live Temps Plot
         * @description Serve the live temperature plot for the specified location.
         *
         *     Args:
         *         location: Location code (e.g., "nyc", "sfo")
         *
         *     Returns:
         *         SVG image response with live temperature visualization
         */
        get: operations["get_live_temps_plot_api__location__plots_live_temps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{location}/plots/tide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tide Plot
         * @description Generate and serve a tide-only plot for the specified location.
         */
        get: operations["get_tide_plot_api__location__plots_tide_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{location}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location Status
         * @description API endpoint that returns status information for a specific location.
         *
         *     Args:
         *         location: Location code (e.g., 'nyc')
         *
         *     Returns:
         *         Status dictionary for the specified location
         *
         *     Raises:
         *         HTTPException: If the location is not configured
         */
        get: operations["location_status_api__location__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apple-touch-icon-precomposed.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Static Route */
        get: operations["static_route_apple_touch_icon_precomposed_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apple-touch-icon.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Static Route */
        get: operations["static_route_apple_touch_icon_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root Embed Redirect
         * @description Redirect the existing embed route to the default location embed page.
         */
        get: operations["root_embed_redirect_embed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favicon.ico": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Static Route */
        get: operations["static_route_favicon_ico_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legacy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legacy Root Redirect
         * @description Redirect the legacy root path to the default legacy location page.
         */
        get: operations["legacy_root_redirect_legacy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legacy/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legacy All Locations
         * @description Serve a landing page showing all swimming locations with their current water temperatures.
         *
         *     Args:
         *         request: FastAPI request object
         *
         *     Returns:
         *         HTML response with all locations and their water temperatures
         */
        get: operations["legacy_all_locations_legacy_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legacy/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legacy Embed Redirect
         * @description Redirect /legacy/embed to the default legacy location embed page.
         *
         *     Returns:
         *         Redirect response to the NYC embed page
         */
        get: operations["legacy_embed_redirect_legacy_embed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legacy/{location}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legacy Location Index
         * @description Serve the legacy Jinja main page for a specific location.
         *
         *     Args:
         *         request: FastAPI request object
         *         location: Location code (e.g., 'nyc')
         *
         *     Returns:
         *         HTML response with location-specific configuration
         *
         *     Raises:
         *         HTTPException: If the location is not configured
         */
        get: operations["legacy_location_index_legacy__location__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legacy/{location}/currents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legacy Location Currents
         * @description Serve the legacy water current visualization page for the specified location.
         *
         *     Args:
         *         request: FastAPI request object
         *         location: Location code (e.g., "nyc", "san")
         *         shift: Time shift in minutes from current time
         *
         *     Returns:
         *         HTML response with current water conditions
         */
        get: operations["legacy_location_currents_legacy__location__currents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legacy/{location}/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legacy Location Embed
         * @description Serve the legacy embed view for a specific location.
         *
         *     Args:
         *         request: FastAPI request object
         *         location: Location code (e.g., 'nyc')
         *
         *     Returns:
         *         HTML response with location-specific embed
         *
         *     Raises:
         *         HTTPException: If the location is not configured
         */
        get: operations["legacy_location_embed_legacy__location__embed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legacy/{location}/widget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legacy Location Widget
         * @description Serve a legacy widget view for a specific location.
         *
         *     Args:
         *         request: FastAPI request object
         *         location: Location code (e.g., 'nyc')
         *
         *     Returns:
         *         HTML response with location-specific widget
         *
         *     Raises:
         *         HTTPException: If the location is not configured
         */
        get: operations["legacy_location_widget_legacy__location__widget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manifest.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Manifest Json
         * @description Serve the canonical web app manifest for the root-mounted React app.
         */
        get: operations["manifest_json_manifest_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/robots.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Robots Txt
         * @description Serve crawler directives for the canonical site.
         */
        get: operations["robots_txt_robots_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sitemap.xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sitemap Xml
         * @description Serve a sitemap of canonical, indexable pages.
         */
        get: operations["sitemap_xml_sitemap_xml_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{location}/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location Embed
         * @description Serve the existing legacy embed view at its historical URL.
         */
        get: operations["location_embed__location__embed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppBootstrapLocation
         * @description Complete frontend bootstrap data for one location.
         */
        AppBootstrapLocation: {
            integrations: components["schemas"]["AppExternalIntegrations"];
            metadata: components["schemas"]["AppLocationMetadata"];
        };
        /**
         * AppBootstrapResponse
         * @description Frontend bootstrap payload for app presentation configuration.
         */
        AppBootstrapResponse: {
            /**
             * App Name
             * @description Full application name
             */
            app_name: string;
            /**
             * Default Location Code
             * @description Default location code
             */
            default_location_code: string;
            /**
             * Location Order
             * @description Ordered location codes
             */
            location_order: string[];
            /**
             * Locations
             * @description Per-location frontend bootstrap metadata
             */
            locations: {
                [key: string]: components["schemas"]["AppBootstrapLocation"];
            };
            /**
             * Short Name
             * @description Short application name
             */
            short_name: string;
            /** @description Project source code link */
            source_code_link: components["schemas"]["AppPresentationLink"];
        };
        /**
         * AppExternalIntegrations
         * @description External presentation integrations used by the React app.
         */
        AppExternalIntegrations: {
            /**
             * Transit Routes
             * @description Transit routes to show for a location
             */
            transit_routes?: components["schemas"]["TransitRouteConfig"][];
            /** @description Transit source or citation link */
            transit_source?: components["schemas"]["AppPresentationLink"] | null;
            /** @description Provider-aware webcam configuration */
            webcam?: components["schemas"]["AppWebcamConfig"] | null;
            /** @description Windy forecast iframe configuration */
            windy?: components["schemas"]["AppWindyConfig"] | null;
        };
        /**
         * AppFeatureFlags
         * @description Presentation feature flags for a location in the React app.
         */
        AppFeatureFlags: {
            /**
             * Currents
             * @description Whether to show current UI
             */
            currents: boolean;
            /**
             * Temperature
             * @description Whether to show temperature UI
             */
            temperature: boolean;
            /**
             * Tides
             * @description Whether to show tide UI
             */
            tides: boolean;
            /**
             * Transit
             * @description Whether to show transit UI
             */
            transit: boolean;
            /**
             * Water Movement Detail
             * @description Whether to show water movement detail controls
             */
            water_movement_detail: boolean;
            /**
             * Water Movement Detail Plot Type
             * @description Detail plot endpoint type to use when water movement detail is enabled
             */
            water_movement_detail_plot_type?: ("current_tide" | "tide") | null;
            /**
             * Water Movement Planning
             * @description Whether to show water movement planner controls
             */
            water_movement_planning: boolean;
            /**
             * Webcam
             * @description Whether to show webcam UI
             */
            webcam: boolean;
            /**
             * Windy
             * @description Whether to show Windy forecast UI
             */
            windy: boolean;
        };
        /**
         * AppLocationMetadata
         * @description Presentation metadata for a swimming location.
         */
        AppLocationMetadata: {
            /** @description Trusted HTML citations for configured data sources */
            citations: components["schemas"]["AppSourceCitations"];
            /**
             * Code
             * @description 3-letter location code
             */
            code: string;
            /**
             * Default Temperature Unit
             * @description Default temperature unit for this location's display
             * @enum {string}
             */
            default_temperature_unit: "F" | "C";
            /**
             * Description
             * @description Description of the swimming location
             */
            description: string;
            /** @description Enabled presentation features */
            features: components["schemas"]["AppFeatureFlags"];
            /**
             * Latitude
             * @description Latitude in decimal degrees
             */
            latitude: number;
            /**
             * Longitude
             * @description Longitude in decimal degrees
             */
            longitude: number;
            /**
             * Name
             * @description City or region name
             */
            name: string;
            /**
             * Nav Label
             * @description Short label for location navigation
             */
            nav_label: string;
            /**
             * Swim Location
             * @description Specific swimming spot name
             */
            swim_location: string;
            /**
             * Swim Location Link
             * @description URL for the swimming spot
             */
            swim_location_link: string;
            /** @description Enabled temperature plot capabilities */
            temperature_plots: components["schemas"]["AppTemperaturePlotConfig"];
            /**
             * Timezone
             * @description IANA timezone name
             */
            timezone: string;
        };
        /**
         * AppPresentationLink
         * @description Presentation link metadata for the frontend.
         */
        AppPresentationLink: {
            /**
             * Description
             * @description Optional presentation text associated with the link
             */
            description?: string | null;
            /**
             * Label
             * @description User-facing link label
             */
            label: string;
            /**
             * Url
             * @description Link URL
             */
            url: string;
        };
        /**
         * AppSourceCitations
         * @description Trusted HTML source citations for a location.
         */
        AppSourceCitations: {
            /**
             * Currents
             * @description Trusted HTML citation for current data
             */
            currents?: string | null;
            /**
             * Historical Temperature
             * @description Trusted HTML citation for historical temperature data
             */
            historical_temperature?: string | null;
            /**
             * Live Temperature
             * @description Trusted HTML citation for live temperature data
             */
            live_temperature?: string | null;
            /**
             * Location Info
             * @description Trusted HTML citation for local swimming location info
             */
            location_info?: string | null;
            /**
             * Temperature
             * @description Trusted HTML citation when live and historical temperature data share a source
             */
            temperature?: string | null;
            /**
             * Tides
             * @description Trusted HTML citation for tide data
             */
            tides?: string | null;
        };
        /**
         * AppTemperaturePlotConfig
         * @description Temperature plot capabilities for frontend rendering.
         */
        AppTemperaturePlotConfig: {
            /**
             * Historic
             * @description Whether historical temperature plots are enabled
             */
            historic: boolean;
            /**
             * Live
             * @description Whether the live temperature plot is enabled
             */
            live: boolean;
        };
        /**
         * AppWebcamConfig
         * @description Provider-aware webcam configuration for frontend rendering.
         */
        AppWebcamConfig: {
            /** @description Alternative webcam link */
            alternative?: components["schemas"]["AppPresentationLink"] | null;
            /**
             * Channel Id
             * @description YouTube channel ID for YouTube live webcams
             */
            channel_id?: string | null;
            /**
             * Embed Url
             * @description Embeddable iframe or provider URL when available
             */
            embed_url?: string | null;
            /**
             * Label
             * @description User-facing webcam label
             */
            label: string;
            /**
             * Note
             * @description Short location-specific webcam note
             */
            note?: string | null;
            /** @description Webcam provider/rendering type */
            provider: components["schemas"]["WebcamProvider"];
            /**
             * Script Url
             * @description Provider script URL for legacy script-based embeds
             */
            script_url?: string | null;
            /** @description Primary webcam source or citation link */
            source?: components["schemas"]["AppPresentationLink"] | null;
            /**
             * Watch Url
             * @description External watch page URL when available
             */
            watch_url?: string | null;
        };
        /**
         * AppWindyConfig
         * @description Windy iframe configuration exposed to the frontend.
         */
        AppWindyConfig: {
            /**
             * Level
             * @description Windy level token
             * @constant
             */
            level: "surface";
            /**
             * Metric Temp
             * @description Windy temperature unit token
             * @enum {string}
             */
            metric_temp: "default" | "°F" | "°C";
            /**
             * Metric Wind
             * @description Windy wind unit token
             * @enum {string}
             */
            metric_wind: "default" | "kt" | "mph" | "m/s" | "km/h" | "bft";
            /**
             * Overlay
             * @description Windy overlay token
             * @enum {string}
             */
            overlay: "waves" | "wind";
            /**
             * Product
             * @description Windy product token
             * @enum {string}
             */
            product: "ecmwfWaves" | "ecmwf";
            /**
             * Zoom
             * @description Initial Windy map zoom level
             */
            zoom: number;
        };
        /**
         * CurrentDirection
         * @enum {string}
         */
        CurrentDirection: "flooding" | "ebbing";
        /**
         * CurrentInfo
         * @description Current prediction/observation information for API responses.
         */
        CurrentInfo: {
            /** @description Direction of current (Enum: CurrentDirection, null if non-tidal) */
            direction?: components["schemas"]["CurrentDirection"] | null;
            /**
             * Magnitude
             * @description Current strength in knots
             */
            magnitude: number;
            /**
             * Magnitude Pct
             * @description Relative current strength (0.0-1.0, null if non-tidal), normalized against the peak within the current continuous flood or ebb segment in the available prediction curve.
             */
            magnitude_pct?: number | null;
            /** @description Compact current phase for displays. Tidal prediction values are flood, ebb, slack_before_flood, slack_before_ebb, or slack. Slack phases are assigned when absolute current magnitude is below 0.2 knots; slack_before_* indicates the next non-slack direction predicted by the curve. */
            phase?: components["schemas"]["CurrentPhase"] | null;
            /** @description Contextual slack-to-peak range for prediction-backed current displays; null for observations, non-tidal currents, slack-only data, or incomplete segment context. */
            range?: components["schemas"]["CurrentRange"] | null;
            /** @description Indicates if data is prediction or observation (Enum: DataSourceType) */
            source_type: components["schemas"]["DataSourceType"];
            /**
             * State Description
             * @description Display-ready current state phrase, such as 'strong ebb and building' or 'slack before flood' (null if non-tidal).
             */
            state_description?: string | null;
            /** @description Cycle-relative current strength for non-slack tidal predictions (light, moderate, or strong). Null for slack or non-tidal currents. */
            strength?: components["schemas"]["CurrentStrength"] | null;
            /**
             * Timestamp
             * Format: date-time
             * @description Timestamp of the prediction or observation in the location's local timezone
             */
            timestamp: string;
            /** @description Current trend for non-slack tidal predictions (building, easing, or steady). Null for slack or non-tidal currents. */
            trend?: components["schemas"]["CurrentTrend"] | null;
        };
        /**
         * CurrentPhase
         * @description Compact current phase for API consumers and displays.
         * @enum {string}
         */
        CurrentPhase: "flood" | "ebb" | "slack_before_flood" | "slack_before_ebb" | "slack";
        /**
         * CurrentRange
         * @description Contextual slack-to-peak current range for API responses.
         */
        CurrentRange: {
            /** @description Peak current point for the current continuous flood or ebb segment. */
            peak: components["schemas"]["CurrentRangePoint"];
            /** @description Relevant slack boundary for the current segment and trend. */
            slack: components["schemas"]["CurrentRangePoint"];
        };
        /**
         * CurrentRangePoint
         * @description A contextual point in a current-speed range.
         */
        CurrentRangePoint: {
            /**
             * Magnitude
             * @description Current speed at this point in knots
             */
            magnitude: number;
            /** @description Current phase for this point when applicable; null for slack. */
            phase?: components["schemas"]["CurrentPhase"] | null;
            /**
             * Timestamp
             * Format: date-time
             * @description Timestamp of this current range point in the location's local timezone
             */
            timestamp: string;
            /**
             * Units
             * @description Current speed units
             * @default kt
             */
            units: string;
        };
        /**
         * CurrentStrength
         * @description Cycle-relative current strength for displays.
         * @enum {string}
         */
        CurrentStrength: "light" | "moderate" | "strong";
        /**
         * CurrentTrend
         * @description Whether the current is building or easing.
         * @enum {string}
         */
        CurrentTrend: "building" | "easing" | "steady";
        /**
         * CurrentsResponse
         * @description Complete response for currents API endpoint.
         */
        CurrentsResponse: {
            current: components["schemas"]["CurrentInfo"];
            /**
             * Current Chart Filename
             * @description Filename of the current chart image (only for locations with chart assets)
             */
            current_chart_filename?: string | null;
            /** @description Legacy chart info (only for locations with chart assets) */
            legacy_chart?: components["schemas"]["LegacyChartInfo"] | null;
            location: components["schemas"]["LocationInfo"];
            /** @description Navigation parameters for time shifting */
            navigation: components["schemas"]["NavigationInfo"];
            /**
             * Timestamp
             * Format: date-time
             * @description Timestamp of the prediction in the location's local timezone
             */
            timestamp: string;
        };
        /**
         * DataFrameSummary
         * @description Provides summary statistics for a time-series DataFrame.
         */
        DataFrameSummary: {
            /**
             * Column Names
             * @description List of column names.
             */
            column_names: string[];
            /**
             * Index Frequency
             * @description Inferred frequency of the DataFrame index (e.g., 'H', 'D', 'T'). None if irregular.
             */
            index_frequency?: string | null;
            /**
             * Index Newest
             * @description Newest timestamp in the DataFrame index (timezone-naive). None if empty/non-datetime index.
             */
            index_newest?: string | null;
            /**
             * Index Oldest
             * @description Oldest timestamp in the DataFrame index (timezone-naive). None if empty/non-datetime index.
             */
            index_oldest?: string | null;
            /**
             * Length
             * @description Number of rows in the DataFrame.
             */
            length: number;
            /**
             * Memory Usage Bytes
             * @description Total memory usage of the DataFrame in bytes (including index, deep=True).
             */
            memory_usage_bytes: number;
            /**
             * Missing Values
             * @description Dictionary mapping column names to the count of missing values.
             */
            missing_values: {
                [key: string]: number;
            };
            /**
             * Width
             * @description Number of columns in the DataFrame.
             */
            width: number;
        };
        /**
         * DataSourceType
         * @description Indicates whether data is based on a prediction or an observation.
         * @enum {string}
         */
        DataSourceType: "prediction" | "observation";
        /**
         * FeedStatus
         * @description Represents the status of a single data feed.
         */
        FeedStatus: {
            /**
             * Age Seconds
             * @description Data age in seconds at the time of status check
             */
            age_seconds?: number | null;
            /**
             * Consecutive Failures
             * @description Consecutive failed fetch attempts since the last successful update; resets to zero on success
             */
            consecutive_failures: number;
            /** @description Summary statistics of the feed's DataFrame, if available */
            data_summary?: components["schemas"]["DataFrameSummary"] | null;
            /**
             * Error
             * @description Last error message encountered by the feed, if any
             */
            error?: string | null;
            /**
             * Expiration Seconds
             * @description Configured expiration time in seconds for the feed
             */
            expiration_seconds?: number | null;
            /**
             * Fetch Timestamp
             * @description Timestamp of the last successful data fetch (naive UTC)
             */
            fetch_timestamp?: string | null;
            /** @description Year-level diagnostics for HistoricalTempsFeed. Null for other feeds. */
            historical_temp_status?: components["schemas"]["HistoricalTempStatus"] | null;
            /**
             * Is Expired
             * @description Whether the feed is due for a scheduled refresh or retry attempt
             */
            is_expired: boolean;
            /**
             * Is Healthy
             * @description Whether the data is recent enough to be considered healthy
             */
            is_healthy: boolean;
            /**
             * Location
             * @description Location code associated with the feed
             */
            location: string;
            /**
             * Name
             * @description Class name of the Feed
             */
            name: string;
            /**
             * Next Fetch After
             * @description Timestamp of the next scheduled refresh or retry attempt (naive UTC)
             */
            next_fetch_after?: string | null;
            /**
             * Seconds Until Next Fetch
             * @description Seconds until the next scheduled refresh or retry attempt
             */
            seconds_until_next_fetch?: number | null;
        };
        /**
         * GoodServiceDirection
         * @description GoodService transit direction keys used by route status payloads.
         * @enum {string}
         */
        GoodServiceDirection: "north" | "south";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoricalTempStatus
         * @description Year-level diagnostics for the historical temperature feed.
         */
        HistoricalTempStatus: {
            /**
             * Available Years
             * @description Required years currently available from the year cache.
             */
            available_years: number[];
            /**
             * Cached Years
             * @description All years currently present in the year cache.
             */
            cached_years: number[];
            /**
             * Failed Years
             * @description Year-to-error map from the latest historical fetch attempt.
             */
            failed_years: {
                [key: string]: string;
            };
            /**
             * Fetched Years
             * @description Years fetched successfully during the latest attempt.
             */
            fetched_years: number[];
            /**
             * Missing Years
             * @description Required years not currently available from the year cache.
             */
            missing_years: number[];
            /**
             * Required Years
             * @description Configured years required before historical data is published.
             */
            required_years: number[];
        };
        /**
         * LegacyChartInfo
         * @description Information about legacy tide charts for API responses.
         */
        LegacyChartInfo: {
            /**
             * Chart Filename
             * @description Filename of the legacy chart
             */
            chart_filename: string;
            /**
             * Hours Since Last Tide
             * @description Hours since the last tide event
             */
            hours_since_last_tide: number;
            /** @description Type of last tide (Enum: TideCategory) */
            last_tide_type: components["schemas"]["TideCategory"];
            /**
             * Map Title
             * @description Title for the legacy map
             */
            map_title: string;
        };
        /**
         * LocationConditions
         * @description Complete response for location conditions endpoint.
         *
         *     Fields are conditionally included based on the location's configuration:
         *     - temperature: Only included if the location has a temperature source with live_enabled=True
         *     - tides: Only included if the location has a tide source
         *     - current: Only included if the location has a current source
         */
        LocationConditions: {
            /** @description Current information (if available) */
            current?: components["schemas"]["CurrentInfo"] | null;
            location: components["schemas"]["LocationInfo"];
            /** @description Water temperature information (if available) */
            temperature?: components["schemas"]["TemperatureInfo"] | null;
            /** @description Tide information (if available) */
            tides?: components["schemas"]["TideInfo"] | null;
        };
        /**
         * LocationInfo
         * @description Location information for API responses.
         */
        LocationInfo: {
            /**
             * Code
             * @description Location code (e.g., 'nyc')
             */
            code: string;
            /**
             * Name
             * @description Display name of the location
             */
            name: string;
            /**
             * Swim Location
             * @description Specific swimming location
             */
            swim_location: string;
        };
        /**
         * LocationStatus
         * @description Represents the status of all feeds for a specific location.
         */
        LocationStatus: {
            /**
             * Feeds
             * @description Dictionary mapping feed names to their FeedStatus objects.
             */
            feeds: {
                [key: string]: components["schemas"]["FeedStatus"];
            };
        };
        /**
         * LocationSummary
         * @description Summary information for a swimming location.
         */
        LocationSummary: {
            /**
             * Code
             * @description 3-letter location code
             */
            code: string;
            /**
             * Has Data
             * @description Whether the location can serve data
             */
            has_data: boolean;
            /**
             * Latitude
             * @description Latitude in decimal degrees
             */
            latitude: number;
            /**
             * Longitude
             * @description Longitude in decimal degrees
             */
            longitude: number;
            /**
             * Name
             * @description City or region name
             */
            name: string;
            /**
             * Swim Location
             * @description Specific swimming spot name
             */
            swim_location: string;
        };
        /**
         * NavigationInfo
         * @description Time navigation metadata for current prediction responses.
         */
        NavigationInfo: {
            /**
             * At
             * @description Location-local planner timestamp when the request used at
             */
            at?: string | null;
            /**
             * Current Api Url
             * @deprecated
             * @description Base currents API URL. Legacy hypermedia convenience; removal candidate because the React app can derive this from the location code.
             */
            current_api_url: string;
            /**
             * Next Hour
             * @deprecated
             * @description Minute shift for the next-hour control. Legacy Jinja navigation compatibility; removal candidate once the React planner owns time controls.
             */
            next_hour: number;
            /**
             * Plot Url
             * @description Matching tide/current plot URL
             */
            plot_url: string;
            /**
             * Prev Hour
             * @deprecated
             * @description Minute shift for the previous-hour control. Legacy Jinja navigation compatibility; removal candidate once the React planner owns time controls.
             */
            prev_hour: number;
            /**
             * Shift
             * @description Resolved minute shift from current time
             */
            shift: number;
        };
        /**
         * TemperatureInfo
         * @description Water temperature information for API responses.
         */
        TemperatureInfo: {
            /**
             * Station Name
             * @description Human-readable name of the temperature station
             */
            station_name?: string | null;
            /**
             * Timestamp
             * Format: date-time
             * @description Timestamp of the reading in the location's local timezone
             */
            timestamp: string;
            /**
             * Water Temp C
             * @description Water temperature in degrees Celsius
             */
            water_temp_c: number;
            /**
             * Water Temp F
             * @description Water temperature in degrees Fahrenheit
             */
            water_temp_f: number;
        };
        /**
         * TideCategory
         * @enum {string}
         */
        TideCategory: "low" | "high";
        /**
         * TideEntry
         * @description Individual tide information for API responses.
         */
        TideEntry: {
            /**
             * Prediction
             * @description Height of tide in feet
             */
            prediction: number;
            /**
             * Time
             * Format: date-time
             * @description Timestamp of the tide event in the location's local timezone
             */
            time: string;
            /** @description Type of tide (Enum: TideCategory) */
            type: components["schemas"]["TideCategory"];
        };
        /**
         * TideInfo
         * @description Collection of tide information for API responses.
         */
        TideInfo: {
            /**
             * Next
             * @description Upcoming tides
             */
            next: components["schemas"]["TideEntry"][];
            /**
             * Past
             * @description Recently occurred tides
             */
            past: components["schemas"]["TideEntry"][];
            /** @description Point-in-time estimated tide state, null when the derived tide curve is unavailable */
            state?: components["schemas"]["TideState"] | null;
        };
        /**
         * TideState
         * @description Point-in-time estimated tide state for API responses.
         */
        TideState: {
            /**
             * Estimated Height
             * @description Estimated tide height in feet, derived from the available tide prediction curve
             */
            estimated_height: number;
            /**
             * Height Pct
             * @description Estimated normalized tide height from 0.0 to 1.0 between the surrounding low/high tide range; null when unavailable
             */
            height_pct?: number | null;
            /**
             * Timestamp
             * Format: date-time
             * @description Timestamp of the tide-state estimate in the location's local timezone
             */
            timestamp: string;
            /** @description Estimated tide trend at the timestamp */
            trend: components["schemas"]["TideTrend"];
            /**
             * Units
             * @description Tide height units
             * @default ft
             */
            units: string;
        };
        /**
         * TideTrend
         * @description Whether the tide height is rising or falling.
         * @enum {string}
         */
        TideTrend: "rising" | "falling" | "steady";
        /**
         * TransitRouteConfig
         * @description Transit route metadata for frontend status cards.
         */
        TransitRouteConfig: {
            /** @description GoodService direction key to show for this route */
            goodservice_direction: components["schemas"]["GoodServiceDirection"];
            /**
             * Goodservice Route Id
             * @description GoodService route ID
             */
            goodservice_route_id: string;
            /**
             * Icon Url
             * @description Optional route icon URL
             */
            icon_url?: string | null;
            /**
             * Label
             * @description User-facing route label
             */
            label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WebcamProvider
         * @description Supported frontend webcam provider/rendering types.
         * @enum {string}
         */
        WebcamProvider: "youtube_live" | "iframe" | "earthcam_embed" | "external_link";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    app_bootstrap_api_app_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppBootstrapResponse"];
                };
            };
        };
    };
    healthy_status_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    healthy_status_api_healthy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    list_locations_api_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationSummary"][];
                };
            };
        };
    };
    all_locations_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["LocationStatus"];
                    };
                };
            };
        };
    };
    location_conditions_api__location__conditions_get: {
        parameters: {
            query?: {
                shift?: number;
                at?: string | null;
            };
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationConditions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    location_currents_api__location__currents_get: {
        parameters: {
            query?: {
                shift?: number;
                at?: string | null;
            };
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_tide_plot_api__location__plots_current_tide_get: {
        parameters: {
            query?: {
                shift?: number;
                at?: string | null;
            };
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_historic_temps_plot_api__location__plots_historic_temps_get: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_temps_plot_api__location__plots_live_temps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tide_plot_api__location__plots_tide_get: {
        parameters: {
            query?: {
                shift?: number;
                at?: string | null;
            };
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    location_status_api__location__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    static_route_apple_touch_icon_precomposed_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    static_route_apple_touch_icon_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root_embed_redirect_embed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    static_route_favicon_ico_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    legacy_root_redirect_legacy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    legacy_all_locations_legacy_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    legacy_embed_redirect_legacy_embed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    legacy_location_index_legacy__location__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_location_currents_legacy__location__currents_get: {
        parameters: {
            query?: {
                shift?: number;
            };
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_location_embed_legacy__location__embed_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legacy_location_widget_legacy__location__widget_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manifest_json_manifest_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    robots_txt_robots_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sitemap_xml_sitemap_xml_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    location_embed__location__embed_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
