/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root Index
         * @description Redirect root path to default location (NYC).
         *
         *     TODO: Use cookies to redirect to last used or saved location.
         */
        get: operations["root_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * View All Locations
         * @description Serve a landing page showing all swimming locations with their current water temperatures.
         *
         *     Args:
         *         request: FastAPI request object
         *
         *     Returns:
         *         HTML response with all locations and their water temperatures
         */
        get: operations["view_all_locations_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App Bootstrap
         * @description Return non-secret presentation metadata for the React app.
         */
        get: operations["app_bootstrap_api_app_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthy Status
         * @description API endpoint for service health check (used by Cloud Run).
         *
         *     Returns 200 if at least one location can serve data (fresh or stale).
         *     Returns 503 only if NO location has any data available.
         *
         *     This lenient check ensures single station outages don't mark the entire
         *     service unhealthy. For detailed per-feed health status, use /api/status.
         *
         *     Returns:
         *         True if service can serve at least one location
         *         Status code 200 if healthy, 503 if not healthy
         */
        get: operations["healthy_status_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/healthy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthy Status
         * @description API endpoint for service health check (used by Cloud Run).
         *
         *     Returns 200 if at least one location can serve data (fresh or stale).
         *     Returns 503 only if NO location has any data available.
         *
         *     This lenient check ensures single station outages don't mark the entire
         *     service unhealthy. For detailed per-feed health status, use /api/status.
         *
         *     Returns:
         *         True if service can serve at least one location
         *         Status code 200 if healthy, 503 if not healthy
         */
        get: operations["healthy_status_api_healthy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Locations
         * @description API endpoint that returns a list of all configured swimming locations.
         *
         *     Returns a summary of each location including code, name, coordinates,
         *     and whether data is currently available.
         *
         *     Returns:
         *         List of LocationSummary objects for all configured locations
         */
        get: operations["list_locations_api_locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All Locations Status
         * @description API endpoint that returns status information for all configured locations.
         *
         *     Returns:
         *         Dictionary mapping location codes to their status dictionaries
         *
         *     Raises:
         *         HTTPException: If no locations are configured
         */
        get: operations["all_locations_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{location}/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location Conditions
         * @description API endpoint that returns tide and temperature data for a specific location.
         *
         *     Args:
         *         location: Location code (e.g., 'nyc')
         *
         *     Returns:
         *         JSON response with tide and temperature information
         *
         *     Raises:
         *         HTTPException: If the location is not configured
         */
        get: operations["location_conditions_api__location__conditions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{location}/currents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location Currents
         * @description API endpoint that returns current predictions for a specific location.
         *
         *     Args:
         *         location: Location code (e.g., 'nyc')
         *         shift: Time shift in minutes from current time (optional)
         *
         *     Returns:
         *         CurrentsResponse object with current prediction details
         *
         *     Raises:
         *         HTTPException: If the location is not configured or doesn't support currents
         */
        get: operations["location_currents_api__location__currents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{location}/plots/current_tide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Tide Plot
         * @description Generate and serve a tide and current plot for the specified location.
         *
         *     Args:
         *         location: Location code (e.g., "nyc", "san")
         *         shift: Time shift in minutes from current time
         *
         *     Returns:
         *         SVG image response with tide and current visualization
         */
        get: operations["get_current_tide_plot_api__location__plots_current_tide_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{location}/plots/historic_temps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Historic Temps Plot
         * @description Serve a historic temperature plot for the specified location.
         *
         *     Args:
         *         location: Location code (e.g., "nyc", "sfo")
         *         period: Time period - "2mo" for 2-month or "12mo" for full year
         *
         *     Returns:
         *         SVG image response with historic temperature visualization
         */
        get: operations["get_historic_temps_plot_api__location__plots_historic_temps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{location}/plots/live_temps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Live Temps Plot
         * @description Serve the live temperature plot for the specified location.
         *
         *     Args:
         *         location: Location code (e.g., "nyc", "sfo")
         *
         *     Returns:
         *         SVG image response with live temperature visualization
         */
        get: operations["get_live_temps_plot_api__location__plots_live_temps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{location}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location Status
         * @description API endpoint that returns status information for a specific location.
         *
         *     Args:
         *         location: Location code (e.g., 'nyc')
         *
         *     Returns:
         *         Status dictionary for the specified location
         *
         *     Raises:
         *         HTTPException: If the location is not configured
         */
        get: operations["location_status_api__location__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apple-touch-icon-precomposed.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Static Route */
        get: operations["static_route_apple_touch_icon_precomposed_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apple-touch-icon.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Static Route */
        get: operations["static_route_apple_touch_icon_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root Embed Redirect
         * @description Redirect /embed to the default location embed page (NYC).
         *
         *     Returns:
         *         Redirect response to the NYC embed page
         */
        get: operations["root_embed_redirect_embed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favicon.ico": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Static Route */
        get: operations["static_route_favicon_ico_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manifest.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Static Route */
        get: operations["static_route_manifest_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/robots.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Robots Txt
         * @description Serve crawler directives for the canonical site.
         */
        get: operations["robots_txt_robots_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sitemap.xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sitemap Xml
         * @description Serve a sitemap of canonical, indexable pages.
         */
        get: operations["sitemap_xml_sitemap_xml_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{location}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location Index
         * @description Serve the main page for a specific location.
         *
         *     Args:
         *         request: FastAPI request object
         *         location: Location code (e.g., 'nyc')
         *
         *     Returns:
         *         HTML response with location-specific configuration
         *
         *     Raises:
         *         HTTPException: If the location is not configured
         */
        get: operations["location_index__location__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{location}/currents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location Currents
         * @description Serve the water current visualization page for the specified location.
         *
         *     Args:
         *         request: FastAPI request object
         *         location: Location code (e.g., "nyc", "san")
         *         shift: Time shift in minutes from current time
         *
         *     Returns:
         *         HTML response with current water conditions
         */
        get: operations["location_currents__location__currents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{location}/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location Embed
         * @description Serve the embed view for a specific location for embedding in other websites.
         *
         *     Args:
         *         request: FastAPI request object
         *         location: Location code (e.g., 'nyc')
         *
         *     Returns:
         *         HTML response with location-specific embed
         *
         *     Raises:
         *         HTTPException: If the location is not configured
         */
        get: operations["location_embed__location__embed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{location}/widget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location Widget
         * @description Serve a widget view for a specific location.
         *
         *     Args:
         *         request: FastAPI request object
         *         location: Location code (e.g., 'nyc')
         *
         *     Returns:
         *         HTML response with location-specific widget
         *
         *     Raises:
         *         HTTPException: If the location is not configured
         */
        get: operations["location_widget__location__widget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppBootstrapLocation
         * @description Complete frontend bootstrap data for one location.
         */
        AppBootstrapLocation: {
            integrations: components["schemas"]["AppExternalIntegrations"];
            metadata: components["schemas"]["AppLocationMetadata"];
        };
        /**
         * AppBootstrapResponse
         * @description Frontend bootstrap payload for app presentation configuration.
         */
        AppBootstrapResponse: {
            /**
             * App Name
             * @description Full application name
             */
            app_name: string;
            /**
             * Default Location Code
             * @description Default location code
             */
            default_location_code: string;
            /**
             * Location Order
             * @description Ordered location codes
             */
            location_order: string[];
            /**
             * Locations
             * @description Per-location frontend bootstrap metadata
             */
            locations: {
                [key: string]: components["schemas"]["AppBootstrapLocation"];
            };
            /** @description Installable app manifest metadata */
            manifest: components["schemas"]["AppManifestMetadata"];
            /**
             * Short Name
             * @description Short application name
             */
            short_name: string;
        };
        /**
         * AppExternalIntegrations
         * @description External presentation integrations used by the React app.
         */
        AppExternalIntegrations: {
            /**
             * Transit Routes
             * @description Transit routes to show for a location
             */
            transit_routes?: components["schemas"]["TransitRouteConfig"][];
            /** @description YouTube live embed configuration */
            youtube_live?: components["schemas"]["YouTubeLiveConfig"] | null;
        };
        /**
         * AppFeatureFlags
         * @description Presentation feature flags for a location in the React app.
         */
        AppFeatureFlags: {
            /**
             * Currents
             * @description Whether to show current UI
             */
            currents: boolean;
            /**
             * Temperature
             * @description Whether to show temperature UI
             */
            temperature: boolean;
            /**
             * Tides
             * @description Whether to show tide UI
             */
            tides: boolean;
            /**
             * Transit
             * @description Whether to show transit UI
             */
            transit: boolean;
            /**
             * Webcam
             * @description Whether to show webcam UI
             */
            webcam: boolean;
            /**
             * Windy
             * @description Whether to show Windy forecast UI
             */
            windy: boolean;
        };
        /**
         * AppLocationMetadata
         * @description Presentation metadata for a swimming location.
         */
        AppLocationMetadata: {
            /** @description Trusted HTML citations for configured data sources */
            citations: components["schemas"]["AppSourceCitations"];
            /**
             * Code
             * @description 3-letter location code
             */
            code: string;
            /**
             * Description
             * @description Description of the swimming location
             */
            description: string;
            /** @description Enabled presentation features */
            features: components["schemas"]["AppFeatureFlags"];
            /**
             * Latitude
             * @description Latitude in decimal degrees
             */
            latitude: number;
            /**
             * Longitude
             * @description Longitude in decimal degrees
             */
            longitude: number;
            /**
             * Name
             * @description City or region name
             */
            name: string;
            /**
             * Nav Label
             * @description Short label for location navigation
             */
            nav_label: string;
            /**
             * Swim Location
             * @description Specific swimming spot name
             */
            swim_location: string;
            /**
             * Swim Location Link
             * @description URL for the swimming spot
             */
            swim_location_link: string;
            /**
             * Timezone
             * @description IANA timezone name
             */
            timezone: string;
        };
        /**
         * AppManifestMetadata
         * @description Installable web app manifest metadata exposed to the frontend.
         */
        AppManifestMetadata: {
            /**
             * Background Color
             * @description Background color
             */
            background_color: string;
            /**
             * Display
             * @description Manifest display mode
             */
            display: string;
            /**
             * Name
             * @description Full web app name
             */
            name: string;
            /**
             * Scope
             * @description Manifest scope
             */
            scope: string;
            /**
             * Short Name
             * @description Short web app name
             */
            short_name: string;
            /**
             * Start Url
             * @description Manifest start URL
             */
            start_url: string;
            /**
             * Theme Color
             * @description Theme color
             */
            theme_color: string;
        };
        /**
         * AppSourceCitations
         * @description Trusted HTML source citations for a location.
         */
        AppSourceCitations: {
            /**
             * Currents
             * @description Trusted HTML citation for current data
             */
            currents?: string | null;
            /**
             * Temperature
             * @description Trusted HTML citation for temperature data
             */
            temperature?: string | null;
            /**
             * Tides
             * @description Trusted HTML citation for tide data
             */
            tides?: string | null;
        };
        /**
         * CurrentDirection
         * @enum {string}
         */
        CurrentDirection: "flooding" | "ebbing";
        /**
         * CurrentInfo
         * @description Current prediction/observation information for API responses.
         */
        CurrentInfo: {
            /** @description Direction of current (Enum: CurrentDirection, null if non-tidal) */
            direction?: components["schemas"]["CurrentDirection"] | null;
            /**
             * Magnitude
             * @description Current strength in knots
             */
            magnitude: number;
            /**
             * Magnitude Pct
             * @description Relative current strength (0.0-1.0, null if non-tidal), normalized against the nearest local flood/ebb peak in the available prediction curve.
             */
            magnitude_pct?: number | null;
            /** @description Compact current phase for displays. Tidal prediction values are flood, ebb, slack_before_flood, slack_before_ebb, or slack. Slack phases are assigned when absolute current magnitude is below 0.2 knots; slack_before_* indicates the next non-slack direction predicted by the curve. */
            phase?: components["schemas"]["CurrentPhase"] | null;
            /** @description Indicates if data is prediction or observation (Enum: DataSourceType) */
            source_type: components["schemas"]["DataSourceType"];
            /**
             * State Description
             * @description Display-ready current state phrase, such as 'strong ebb and building' or 'slack before flood' (null if non-tidal).
             */
            state_description?: string | null;
            /** @description Cycle-relative current strength for non-slack tidal predictions (light, moderate, or strong). Null for slack or non-tidal currents. */
            strength?: components["schemas"]["CurrentStrength"] | null;
            /**
             * Timestamp
             * @description ISO 8601 formatted timestamp of the prediction (in location's local timezone)
             */
            timestamp: string;
            /** @description Current trend for non-slack tidal predictions (building, easing, or steady). Null for slack or non-tidal currents. */
            trend?: components["schemas"]["CurrentTrend"] | null;
        };
        /**
         * CurrentPhase
         * @description Compact current phase for API consumers and displays.
         * @enum {string}
         */
        CurrentPhase: "flood" | "ebb" | "slack_before_flood" | "slack_before_ebb" | "slack";
        /**
         * CurrentStrength
         * @description Cycle-relative current strength for displays.
         * @enum {string}
         */
        CurrentStrength: "light" | "moderate" | "strong";
        /**
         * CurrentTrend
         * @description Whether the current is building or easing.
         * @enum {string}
         */
        CurrentTrend: "building" | "easing" | "steady";
        /**
         * CurrentsResponse
         * @description Complete response for currents API endpoint.
         */
        CurrentsResponse: {
            current: components["schemas"]["CurrentInfo"];
            /**
             * Current Chart Filename
             * @description Filename of the current chart image (only for locations with chart assets)
             */
            current_chart_filename?: string | null;
            /** @description Legacy chart info (only for locations with chart assets) */
            legacy_chart?: components["schemas"]["LegacyChartInfo"] | null;
            location: components["schemas"]["LocationInfo"];
            /**
             * Navigation
             * @description Navigation parameters for time shifting
             */
            navigation: {
                [key: string]: unknown;
            };
            /**
             * Timestamp
             * @description ISO 8601 formatted timestamp of the prediction (in location's local timezone)
             */
            timestamp: string;
        };
        /**
         * DataFrameSummary
         * @description Provides summary statistics for a time-series DataFrame.
         */
        DataFrameSummary: {
            /**
             * Column Names
             * @description List of column names.
             */
            column_names: string[];
            /**
             * Index Frequency
             * @description Inferred frequency of the DataFrame index (e.g., 'H', 'D', 'T'). None if irregular.
             */
            index_frequency?: string | null;
            /**
             * Index Newest
             * @description Newest timestamp in the DataFrame index (timezone-naive). None if empty/non-datetime index.
             */
            index_newest?: string | null;
            /**
             * Index Oldest
             * @description Oldest timestamp in the DataFrame index (timezone-naive). None if empty/non-datetime index.
             */
            index_oldest?: string | null;
            /**
             * Length
             * @description Number of rows in the DataFrame.
             */
            length: number;
            /**
             * Memory Usage Bytes
             * @description Total memory usage of the DataFrame in bytes (including index, deep=True).
             */
            memory_usage_bytes: number;
            /**
             * Missing Values
             * @description Dictionary mapping column names to the count of missing values.
             */
            missing_values: {
                [key: string]: number;
            };
            /**
             * Width
             * @description Number of columns in the DataFrame.
             */
            width: number;
        };
        /**
         * DataSourceType
         * @description Indicates whether data is based on a prediction or an observation.
         * @enum {string}
         */
        DataSourceType: "prediction" | "observation";
        /**
         * FeedStatus
         * @description Represents the status of a single data feed.
         */
        FeedStatus: {
            /**
             * Age Seconds
             * @description Data age in seconds at the time of status check
             */
            age_seconds?: number | null;
            /** @description Summary statistics of the feed's DataFrame, if available */
            data_summary?: components["schemas"]["DataFrameSummary"] | null;
            /**
             * Error
             * @description Last error message encountered by the feed, if any
             */
            error?: string | null;
            /**
             * Expiration Seconds
             * @description Configured expiration time in seconds for the feed
             */
            expiration_seconds?: number | null;
            /**
             * Fetch Timestamp
             * @description Timestamp of the last successful data fetch (naive UTC)
             */
            fetch_timestamp?: string | null;
            /**
             * Is Expired
             * @description Whether the data is considered expired
             */
            is_expired: boolean;
            /**
             * Is Healthy
             * @description Whether the data is recent enough to be considered healthy
             */
            is_healthy: boolean;
            /**
             * Location
             * @description Location code associated with the feed
             */
            location: string;
            /**
             * Name
             * @description Class name of the Feed
             */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LegacyChartInfo
         * @description Information about legacy tide charts for API responses.
         */
        LegacyChartInfo: {
            /**
             * Chart Filename
             * @description Filename of the legacy chart
             */
            chart_filename: string;
            /**
             * Hours Since Last Tide
             * @description Hours since the last tide event
             */
            hours_since_last_tide: number;
            /** @description Type of last tide (Enum: TideCategory) */
            last_tide_type: components["schemas"]["TideCategory"];
            /**
             * Map Title
             * @description Title for the legacy map
             */
            map_title: string;
        };
        /**
         * LocationConditions
         * @description Complete response for location conditions endpoint.
         *
         *     Fields are conditionally included based on the location's configuration:
         *     - temperature: Only included if the location has a temperature source with live_enabled=True
         *     - tides: Only included if the location has a tide source
         *     - current: Only included if the location has a current source
         */
        LocationConditions: {
            /** @description Current information (if available) */
            current?: components["schemas"]["CurrentInfo"] | null;
            location: components["schemas"]["LocationInfo"];
            /** @description Water temperature information (if available) */
            temperature?: components["schemas"]["TemperatureInfo"] | null;
            /** @description Tide information (if available) */
            tides?: components["schemas"]["TideInfo"] | null;
        };
        /**
         * LocationInfo
         * @description Location information for API responses.
         */
        LocationInfo: {
            /**
             * Code
             * @description Location code (e.g., 'nyc')
             */
            code: string;
            /**
             * Name
             * @description Display name of the location
             */
            name: string;
            /**
             * Swim Location
             * @description Specific swimming location
             */
            swim_location: string;
        };
        /**
         * LocationStatus
         * @description Represents the status of all feeds for a specific location.
         */
        LocationStatus: {
            /**
             * Feeds
             * @description Dictionary mapping feed names to their FeedStatus objects.
             */
            feeds: {
                [key: string]: components["schemas"]["FeedStatus"];
            };
        };
        /**
         * LocationSummary
         * @description Summary information for a swimming location.
         */
        LocationSummary: {
            /**
             * Code
             * @description 3-letter location code
             */
            code: string;
            /**
             * Has Data
             * @description Whether the location can serve data
             */
            has_data: boolean;
            /**
             * Latitude
             * @description Latitude in decimal degrees
             */
            latitude: number;
            /**
             * Longitude
             * @description Longitude in decimal degrees
             */
            longitude: number;
            /**
             * Name
             * @description City or region name
             */
            name: string;
            /**
             * Swim Location
             * @description Specific swimming spot name
             */
            swim_location: string;
        };
        /**
         * TemperatureInfo
         * @description Water temperature information for API responses.
         */
        TemperatureInfo: {
            /**
             * Station Name
             * @description Human-readable name of the temperature station
             */
            station_name?: string | null;
            /**
             * Timestamp
             * @description ISO 8601 formatted timestamp of the reading (in location's local timezone)
             */
            timestamp: string;
            /**
             * Units
             * @description Temperature units (F for Fahrenheit)
             * @default F
             */
            units: string;
            /**
             * Water Temp
             * @description Water temperature in degrees
             */
            water_temp: number;
        };
        /**
         * TideCategory
         * @enum {string}
         */
        TideCategory: "low" | "high";
        /**
         * TideEntry
         * @description Individual tide information for API responses.
         */
        TideEntry: {
            /**
             * Prediction
             * @description Height of tide in feet
             */
            prediction: number;
            /**
             * Time
             * @description ISO 8601 formatted timestamp of the tide event (in location's local timezone)
             */
            time: string;
            /** @description Type of tide (Enum: TideCategory) */
            type: components["schemas"]["TideCategory"];
        };
        /**
         * TideInfo
         * @description Collection of tide information for API responses.
         */
        TideInfo: {
            /**
             * Next
             * @description Upcoming tides
             */
            next: components["schemas"]["TideEntry"][];
            /**
             * Past
             * @description Recently occurred tides
             */
            past: components["schemas"]["TideEntry"][];
        };
        /**
         * TransitRouteConfig
         * @description Transit route metadata for frontend status cards.
         */
        TransitRouteConfig: {
            /**
             * Goodservice Route Id
             * @description GoodService route ID
             */
            goodservice_route_id: string;
            /**
             * Icon Url
             * @description Optional route icon URL
             */
            icon_url?: string | null;
            /**
             * Label
             * @description User-facing route label
             */
            label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * YouTubeLiveConfig
         * @description YouTube live embed configuration for a frontend integration.
         */
        YouTubeLiveConfig: {
            /**
             * Channel Id
             * @description YouTube channel ID
             */
            channel_id: string;
            /**
             * Embed Url
             * @description YouTube live embed URL
             */
            embed_url: string;
            /**
             * Watch Url
             * @description YouTube live watch URL
             */
            watch_url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    view_all_locations_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    app_bootstrap_api_app_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppBootstrapResponse"];
                };
            };
        };
    };
    healthy_status_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    healthy_status_api_healthy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    list_locations_api_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationSummary"][];
                };
            };
        };
    };
    all_locations_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["LocationStatus"];
                    };
                };
            };
        };
    };
    location_conditions_api__location__conditions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationConditions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    location_currents_api__location__currents_get: {
        parameters: {
            query?: {
                shift?: number;
            };
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_tide_plot_api__location__plots_current_tide_get: {
        parameters: {
            query?: {
                shift?: number;
            };
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_historic_temps_plot_api__location__plots_historic_temps_get: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_temps_plot_api__location__plots_live_temps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    location_status_api__location__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    static_route_apple_touch_icon_precomposed_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    static_route_apple_touch_icon_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root_embed_redirect_embed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    static_route_favicon_ico_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    static_route_manifest_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    robots_txt_robots_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sitemap_xml_sitemap_xml_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    location_index__location__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    location_currents__location__currents_get: {
        parameters: {
            query?: {
                shift?: number;
            };
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    location_embed__location__embed_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    location_widget__location__widget_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
