name: Pytype
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Pytype
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - run: pip install poetry
    - run: poetry install
    - run: pytype $(git ls-files '*.py')
